### ISSUE TITLE
CavEX

### ISSUE THREAD

**Issue by Alexis20000** [OpenShopChannel/outdated-apps#90] opened 2023-08-23 18:24 UTC
### Currently Listed Version

Alpha 0.2.1

### URL to new version

https://github.com/xtreme8000/CavEX

### Version of Updated App

Alpha 0.2.1

### Select listing type

Apps

### More Information

updated version of the app is Alpha 0.2.1 but it is a new version. update the app on the homebrew browser (Open shop channel) please

**Comment by GabubuAvailable** [comment] 2023-09-06 11:27
Duplicate of #89

**Closed as completed by GabubuAvailable** 2023-09-06 11:27 UTC
Labels: duplicate
