### ISSUE TITLE
CavEX

### ISSUE THREAD

**Issue by Alexis20000** [OpenShopChannel/outdated-apps#91] opened 2023-08-24 14:40 UTC
### Currently Listed Version

Alpha 0.2.1

### URL to new version

https://github.com/xtreme8000/CavEX

### Version of Updated App

Alpha 0.2.1

### Select listing type

Apps

### More Information

Please Update the app please is the new version of the alpha 0.2.1 but is a real new version of the alpha 0.2.1 please update the app please🥺🥺🥺🥺🥺

**Comment by GabubuAvailable** [comment] 2023-09-06 11:28
Duplicate of #89

**Closed as completed by GabubuAvailable** 2023-09-06 11:28 UTC
Labels: duplicate
